In [52]:
import numpy as np
import math

l1 = [1,2,3]
nl1 = np.array(l1)
print(nl1)

[1 2 3]


In [36]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [37]:
np.zeros(2)

array([0., 0.])

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.arange(0,100,10).shape

(10,)

In [40]:
nplinspace = np.linspace(10,99,15)
print(nplinspace)
nplinspace.shape

[10.         16.35714286 22.71428571 29.07142857 35.42857143 41.78571429
 48.14285714 54.5        60.85714286 67.21428571 73.57142857 79.92857143
 86.28571429 92.64285714 99.        ]


(15,)

In [41]:
nplinspace.ndim

1

In [42]:
np_id = np.identity(3)

In [43]:
np_id[0][2] = 5

In [44]:
print(np_id)

[[1. 0. 5.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
np_id.min()
np_id.max()
np_id[1][0] = 4

In [46]:
print(np_id)
all_sum = np_id.sum()
row_axis_sum = np_id.sum(axis=0)
col_axis_sum = np_id.sum(axis=1)
print(all_sum,row_axis_sum,col_axis_sum)

[[1. 0. 5.]
 [4. 1. 0.]
 [0. 0. 1.]]
12.0 [5. 1. 6.] [6. 5. 1.]


In [55]:
np_rand = np.random.rand(3,5)
print(np_rand)
np_rand*10


[[0.6387969  0.53554899 0.62445497 0.84483826 0.52784884]
 [0.18726893 0.0167934  0.39534639 0.34500257 0.30874175]
 [0.08042981 0.99784402 0.62947622 0.47377859 0.56205179]]


array([[6.38796896, 5.35548989, 6.2445497 , 8.44838258, 5.27848842],
       [1.87268933, 0.16793397, 3.95346392, 3.45002566, 3.08741753],
       [0.80429815, 9.97844017, 6.29476219, 4.73778587, 5.62051794]])

In [63]:
new_np = np_id.dot(np_rand)
print(new_np)
np_rand_slice = np_rand[0:,0:3]
print(np_rand_slice)

[[1.04094597 5.52476908 3.77183606 3.21373119 3.33810781]
 [2.74245652 2.15898935 2.89316627 3.7243556  2.42013712]
 [0.08042981 0.99784402 0.62947622 0.47377859 0.56205179]]
[[0.6387969  0.53554899 0.62445497]
 [0.18726893 0.0167934  0.39534639]
 [0.08042981 0.99784402 0.62947622]]


In [69]:
new_np[:,[0,1]]

array([[1.04094597, 5.52476908],
       [2.74245652, 2.15898935],
       [0.08042981, 0.99784402]])

In [79]:
new_np.sort(axis=0)
print(new_np)
new_np.sum(axis=1).reshape(3,1)

[[0.08042981 0.47377859 0.56205179 0.62947622 0.99784402]
 [1.04094597 2.42013712 2.74245652 2.89316627 3.7243556 ]
 [2.15898935 3.21373119 3.33810781 3.77183606 5.52476908]]


array([[ 2.74358043],
       [12.82106148],
       [18.0074335 ]])